# Usa una imagen base oficial de Node.js
FROM node:18

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código
COPY . .

# Compila la aplicación para producción
RUN npm run build

# Expone el puerto de la aplicación
EXPOSE 5173

# Comando para correr Vite en modo producción
CMD ["npm", "run", "preview"]