version: "3"
services:
  backend:
    build:
      context: ./server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - frontend
    networks:
      - app-network

  frontend:
    build:
      context: ./client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
